hw34/account/urls.py
from django.conf.urls import url
from .views import LoginFormView, RegisterFormView, LogoutView, UserChangeFormView
from .views import change_password, profile_view
app_name = 'account'

urlpatterns = [
    url(r'^login/$', LoginFormView.as_view(), name='login'),
    url(r'^signup/$', RegisterFormView.as_view(), name='reg'),
    url(r'^password/$', change_password, name='change_pass'),
    url(r'^settings/$', UserChangeFormView.as_view(), name='settings'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^$', profile_view, name='profile'),

]

hw34/hw3/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views
urlpatterns = [
    url(r'^admin/',include(admin.site.urls)),
    url(r'^$', views.index, name='index'),
    url(r'^account/', include('account.urls')),
    url(r'^', include('roadmap.urls')),
]

hw34/roadmap/urls.py
from django.conf.urls import url
from . import views

app_name = 'roadmap'
urlpatterns = [
    url(r'^task/(?P<pk>\d+)/$', views.task_detail, name='task'),
    # url(r'^task/new/$', views.task_new, name='task_new'),
    url(r'^task/(?P<pk>\d+)/edit/$', views.task_update, name='task_edit'),
    url(r'^task/(?P<pk>\d+)/delete/$', views.task_delete, name='task_delete'),
    url(r'^roadmaps/$', views.roadmaps_show, name='roadmaps'),
    url(r'^roadmaps/(?P<pk>\d+)/$', views.roadmap_detail, name='roadmap'),
    url(r'^roadmaps/new/$', views.roadmap_new, name='roadmap_new'),
    url(r'^roadmaps/(?P<pk>\d+)/delete/$', views.roadmap_delete, name='roadmap_delete'),
    url(r'^roadmaps/(?P<pk>\d+)/task_new/$', views.task_new, name='task_new'),
    # url(r'^roadmaps/stats/$', views.roadmap_stats, name='roadmap_stats'),
    url(r'^roadmaps/stats/$', views.roadmap_stats, name='roadmap_stats')
   ]

hw34/account/models.py
from django.db import models
from django.core.mail import send_mail
from django.utils import six, timezone
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin,AbstractUser
from .utils import UserManager

# http://techqa.info/programming/question/18769729/django---removing-username-from-user-model
# поч так а не иначе


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField('Email', unique=True)
    phone = models.CharField('Номер телефона', max_length=15)
    last_name = models.CharField('Фамилия', max_length=50)
    first_name = models.CharField('Имя', max_length=50)
    age = models.PositiveIntegerField('Возраст', null=True, blank=True)
    region = models.CharField('Регион', max_length=50, null=True, blank=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    date_joined = models.DateTimeField(default=timezone.now)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['phone', 'last_name', 'first_name']

    objects = UserManager()

    def clean(self):
        super(User, self).clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Returns the first_name plus the last_name, with a space in between.
        """
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        "Returns the short name for the user."
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """
        Sends an email to this User.
        """
        send_mail(subject, message, from_email, [self.email], **kwargs)

hw34/roadmap/models.py
from datetime import datetime
from django.utils import timezone
from django.db import models
from django.db.models import Max, F, DurationField
from datetime import date, time, timedelta
from account.models import User


class Roadmap(models.Model):
    name = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def today(self):
        today_tasks = Task.objects.filter(estimate=date.today(), roadmap=self)
        return today_tasks

    def filter(self, state):
        state_tasks = Task.objects.filter(state=state, roadmap=self)
        return state_tasks

    def __str__(self):
        return self.name


class Task(models.Model):
    STATE_CHOICES = [
        ('in_progress', 'In progress'),
        ('ready', 'Ready')
    ]

    title = models.CharField(max_length=100)
    state = models.CharField(max_length=12, choices=STATE_CHOICES, default='in_progress')
    estimate = models.DateTimeField()
    created = models.DateTimeField(auto_now_add=True)
    roadmap = models.ForeignKey(Roadmap, on_delete=models.CASCADE)

    def set_score(self):
        max_estimate = Task.objects.all().aggregate(maximum=Max(F('estimate') - F('created'),
                                                                  output_field=DurationField()))
        today = timezone.now()
        points = (today - self.created) / (self.estimate - self.created) + (
                                                (self.estimate - self.created) / max_estimate['maximum'])
        if not hasattr(self, 'score'):
            self.score = Score.objects.create(task=self, points=points)
        else:
            self.score.points = points

    def unset_score(self):
        if hasattr(self, 'score'):
            self.score.delete()

    @property
    def remaining(self):
        """Remains until expiration of the deadline"""
        if self.state == "in_progress":
            return self.estimate - timezone.now()
        else:
            return timedelta(0)

    @property
    def is_failed(self):
        """return true if task is failed"""
        if self.state == "in_progress" and self.estimate < timezone.now():
            return True
        else:
            return False

    @property
    def is_crit(self):
        if self.remaining <= timedelta(days=3) and self.state == 'in_progress' or self.is_failed:
            return True
        else:
            return False

    def __str__(self):
        return self.title


class Score(models.Model):
    task = models.OneToOneField(Task, primary_key=True, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    points = models.DecimalField(max_digits=9, decimal_places=2, default=0)

    def __str__(self):
        return 'Score for ' + self.task.title

hw34/templates/form.html
<!DOCTYPE html>
<html>
<head>
	<title>Test Form for Task</title>
</head>
<body>
	<h1>New task</h1>
    {% if msg %}
        {{ msg }}
    {% endif %}
	<form action="" method="POST">
		<div class="field">
            {{ form.title.errors }}
            <label for="id_subject">Title:</label>
            {{ form.title }}
        </div>
        <div class="field">
            {{ form.state.errors }}
            <label for="id_email">State:</label>
            {{ form.state }}
        </div>
        <div class="field">
            {{ form.estimate.errors }}
            <label for="id_message">Estimate:</label>
            {{ form.estimate }}
        </div>
        <div class="field">
            {{ form.roadmap.errors }}
            <label for="id_message">Roadmap:</label>
            {{ form.roadmap }}
        </div>
		{% csrf_token %}
		<input type="submit" value="Submit">
	</form>
</body>
</html>

hw34/templates/main.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>{%block title%}{% endblock %}</title>
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	
	{%load static%}
	<link rel="stylesheet" href="{%static 'main.css'%}">
	<script
	  src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
	  integrity="sha256-k2WSCIexGzOj3Euiig+TlR8gA0EmPjuc79OEeY5L45g="
	  crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="/">Task Tracker</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="/">Home</a></li>
            <li><a href="/#about">About</a></li>
            <li><a href="/#contact">Contact</a></li>
          </ul>
            {% if user.is_authenticated %}
            <ul class="nav navbar-nav pull-right">
                <li><a href="{% url 'account:profile' %}">Профиль</a></li>
                <li><a href="{% url 'roadmap:roadmaps' %}">Просмотр Roadmap'ов</a></li>
                <li><a href="{% url 'roadmap:roadmap_new' %}">Новый Roadmap</a></li>
                <li><a href="{% url 'account:logout' %}">Выход</a></li>
            </ul>
            {% endif %}
        </div><!--/.nav-collapse -->

      </div>
    </nav>
{% block content %}

{% endblock %}
  </body>
</html>

hw34/templates/roadmap_detail.html
{% extends "main.html" %} {%block title%}Roadmap`s tasks{% endblock %} 
{%block content%}
<div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            
            <div class="modal-body">
                <h3>Вы действительно хотите удалить этот task?</h3>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Нет</button>
                <a class="btn btn-danger btn-ok">Да</a>
            </div>
        </div>
    </div>
</div><div class="wrapper">
    <div class="row col-md-offset-2 col-md-8">
        <h1>Task list for {{ roadmap.name }}</h1>
        <p><a class='btn btn-default' href="{%  url 'roadmap:roadmaps' %}">Back to Roadmaps</a></p>
        <p><a class='btn btn-primary' href="{% url 'roadmap:task_new' pk=roadmap.pk %}">Create new task</a></p>
        <div class="table-responsive ">
        	<table class="table table-hover">
        		{% for task in tasks %}
	            <tr class='row {%if task.is_crit %}danger{% endif %}{% if task.state == "ready" %}success{% endif %}'>
	                <td class='col-md-4'>
	                    <a href="{% url 'roadmap:task' pk=task.pk %}">{{ task.title }}</a></td>
	                <td class='col-md-2'>{{ task.state }}</td>
	                <td class='col-md-2'>{{ task.estimate }}</td>
	                <td class='col-md-2'><a  data-href="{% url 'roadmap:task_delete' pk=task.pk %}" data-toggle="modal" data-target="#confirm-delete" href="#">Delete task</a></td>
	                <td class='col-md-2'>
	                <a href="{% url 'roadmap:task_edit' pk=task.pk %}">Edit task</a></td>
	            </tr>
         		{% endfor %}
        	</table>
		</div>
    </div>
</div>
<script>$('#confirm-delete').on('show.bs.modal', function(e) {
    $(this).find('.btn-ok').attr('href', $(e.relatedTarget).data('href'));
});</script>
{% endblock %}

hw34/templates/roadmap_new.html
{% extends "main.html" %} {%block title%}New roadmap{% endblock %} {%block content%}
<div class="wrapper">
    <div class="row col-md-offset-2 col-md-8">
        <h1>New Roadmap</h1>
        <form action="" method="POST">
            <div class="form-group">
                {{ form.name.errors }}
                <label for="id_name">Name:</label>
                {{ form.name }}
            </div>
            {% csrf_token %}
  			<button type="submit" class="btn btn-default">Submit</button>
        </form>
    </div>
</div>
</body>

</html>
{% endblock %}

hw34/templates/roadmap_stat.html
{% extends "main.html" %} {%block title%}Roadmaps stats{% endblock %} 
{%block content%}

<div class="wrapper">
    <div class="row col-md-offset-2 col-md-8">
    <div class="row">
        <h1>Roadmaps Stats</h1>
        <a class='btn btn-default' href="{%  url 'roadmap:roadmaps' %}">Back to Roadmaps</a>
    </div>
    	<h3>Weekly stats</h3>
        <div class="table-responsive ">
        	<table class="table table-hover">
        		<tr class='row'>
	                <th class='col-md-2'>Week number</a></td>
	                <th class='col-md-4'>Interval</td>
	                <th class='col-md-3'>Tasks created</td>
	                <th class='col-md-3'>Tasks completed</td>
	            </tr>
        		{% for week in weeks %}
	            <tr class='row'>
	                <td class='col-md-2'>{{ week.number }}</a></td>
	                <td class='col-md-4'>{{ week.title }}</td>
	                <td class='col-md-3'>{{ week.tasks_created }}</td>
	                <td class='col-md-3'>{{ week.tasks_completed }}</td>
	            </tr>
         		{% endfor %}
        	</table>
		</div>
		<h3>Monthly stats</h3>
	    <div class="table-responsive ">
        	<table class="table table-hover">
        		<tr class='row'>
	                <th class='col-md-2'>Month</a></td>
	                <th class='col-md-4'>Points earned</td>
	            </tr>
        		{% for month in months %}
	            <tr class='row'>
	                <td class='col-md-2'>{{ month.title }}</a></td>
	                <td class='col-md-4'>{{ month.points_earned }}</td>
	            </tr>
         		{% endfor %}
        	</table>
		</div>
    </div>
</div>
{% endblock %}

hw34/templates/task.html
{% extends "main.html" %} {%block title%}task {{task.pk}}{% endblock %} 
{%block content%}
<div class="wrapper">
    <div class="row col-md-offset-2 col-md-8">
		<h1{%if task.is_crit %} style="color:red;"{%endif%}>{{ task.title }}</h1>
	    <p>Task estimate: {{ task.estimate }} </p>
	    <p>Task state: {{ task.state }} </p>
	    {% if task.score %}<p>Task points: {{ task.score.points }} </p>{% endif %}

	    <a href="{% url 'roadmap:task_edit' pk=task.pk %}">Edit task</a>
	    <p><a class='btn btn-default' href="{%  url 'roadmap:roadmap' pk=task.roadmap.pk %}">Back to Roadmap</a></p>
	</div>
</div>	
</div>
{% endblock %}

hw34/templates/task_edit.html
{% extends "main.html" %} {%block title%}task update{% endblock %} 
{%block content%}
<div class="wrapper">
    <div class="row col-md-offset-2 col-md-8">
	<h1>{{ action }} task</h1>
    {% if msg %}
        {{ msg }}
    {% endif %}
	<form action="" method="POST">
		<div class="field">
            {{ form.title.errors }}
            <label for="id_title">Title:</label>
            {{ form.title }}
        </div>
        {% if action == "Update" %} 
            <div class="field">
                {{ form.state.errors }}
                <label for="id_state">State:</label>
                {{ form.state }}
            </div>
        {% endif %} 
        <div class="field">
            {{ form.estimate.errors }}
            <label for="id_estimate">Estimate:</label>
            {{ form.estimate }}
        </div>

		{% csrf_token %}
		<input type="submit" value="Submit">
	</form>
    </div>  
</div>
{% endblock %}