hw34/hw3/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views
urlpatterns = [
    url(r'^admin/',include(admin.site.urls)),
    url(r'^$', views.index, name='index'),
    url(r'^account/', include('account.urls')),
    url(r'^', include('roadmap.urls')),
]

hw34/roadmap/urls.py
from django.conf.urls import url
from . import views

app_name = 'roadmap'
urlpatterns = [
    url(r'^task/(?P<pk>\d+)/$', views.task_detail, name='task'),
    # url(r'^task/new/$', views.task_new, name='task_new'),
    url(r'^task/(?P<pk>\d+)/edit/$', views.task_update, name='task_edit'),
    url(r'^task/(?P<pk>\d+)/delete/$', views.task_delete, name='task_delete'),
    url(r'^roadmaps/$', views.roadmaps_show, name='roadmaps'),
    url(r'^roadmaps/(?P<pk>\d+)/$', views.roadmap_detail, name='roadmap'),
    url(r'^roadmaps/new/$', views.roadmap_new, name='roadmap_new'),
    url(r'^roadmaps/(?P<pk>\d+)/delete/$', views.roadmap_delete, name='roadmap_delete'),
    url(r'^roadmaps/(?P<pk>\d+)/task_new/$', views.task_new, name='task_new'),
    # url(r'^roadmaps/stats/$', views.roadmap_stats, name='roadmap_stats'),
    url(r'^roadmaps/stats/$', views.roadmap_stats, name='roadmap_stats')
   ]

hw34/roadmap/models.py
from datetime import datetime
from django.utils import timezone
from django.db import models
from django.db.models import Max, F, DurationField
from datetime import date, time, timedelta
from account.models import User


class Roadmap(models.Model):
    name = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def today(self):
        today_tasks = Task.objects.filter(estimate=date.today(), roadmap=self)
        return today_tasks

    def filter(self, state):
        state_tasks = Task.objects.filter(state=state, roadmap=self)
        return state_tasks

    def __str__(self):
        return self.name


class Task(models.Model):
    STATE_CHOICES = [
        ('in_progress', 'In progress'),
        ('ready', 'Ready')
    ]

    title = models.CharField(max_length=100)
    state = models.CharField(max_length=12, choices=STATE_CHOICES, default='in_progress')
    estimate = models.DateTimeField()
    created = models.DateTimeField(auto_now_add=True)
    roadmap = models.ForeignKey(Roadmap, on_delete=models.CASCADE)

    def set_score(self):
        max_estimate = Task.objects.all().aggregate(maximum=Max(F('estimate') - F('created'),
                                                                  output_field=DurationField()))
        today = timezone.now()
        points = (today - self.created) / (self.estimate - self.created) + (
                                                (self.estimate - self.created) / max_estimate['maximum'])
        if not hasattr(self, 'score'):
            self.score = Score.objects.create(task=self, points=points)
        else:
            self.score.points = points

    def unset_score(self):
        if hasattr(self, 'score'):
            self.score.delete()

    @property
    def remaining(self):
        """Remains until expiration of the deadline"""
        if self.state == "in_progress":
            return self.estimate - timezone.now()
        else:
            return timedelta(0)

    @property
    def is_failed(self):
        """return true if task is failed"""
        if self.state == "in_progress" and self.estimate < timezone.now():
            return True
        else:
            return False

    @property
    def is_crit(self):
        if self.remaining <= timedelta(days=3) and self.state == 'in_progress' or self.is_failed:
            return True
        else:
            return False

    def __str__(self):
        return self.title


class Score(models.Model):
    task = models.OneToOneField(Task, primary_key=True, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    points = models.DecimalField(max_digits=9, decimal_places=2, default=0)

    def __str__(self):
        return 'Score for ' + self.task.title

hw34/roadmap/forms.py
from django.forms import ModelForm, SelectDateWidget, ValidationError
from roadmap.models import Task, Roadmap
from datetime import datetime
from django.utils import timezone
from django.urls import reverse


class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'estimate']  #minus roadmap
        widgets = {
            'estimate': SelectDateWidget(years=range(2016, 2050)),
        }

    def clean_estimate(self):
        estimate = self.cleaned_data['estimate']

        if estimate < timezone.now(): # если что надо заменить на datetime.today()
            raise ValidationError("Estimate must be today or later")
        return estimate


class TaskEditForm(ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'state', 'estimate']  # minus roadmap
        widgets = {
            'estimate': SelectDateWidget(years=range(2016, 2050)),
        }

    def clean_estimate(self):
        estimate = self.cleaned_data['estimate']
        if estimate < timezone.now():
            raise ValidationError("Estimate must be today or later")
        return estimate


class RoadmapForm(ModelForm):
    class Meta:
        model = Roadmap
        fields = ['name']

hw34/roadmap/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse_lazy
from django.core.exceptions import PermissionDenied
from django.db import models

from .models import Task, Roadmap, Score
from .forms import TaskForm, TaskEditForm, RoadmapForm

from .utils import stats


@login_required(login_url=reverse_lazy('account:login'))
def task_detail(request, pk):
    task = get_object_or_404(Task, pk=pk)
    if request.user == task.roadmap.user:
        return render(request, 'roadmap/task.html', {'task': task})
    else:
        raise PermissionDenied


@login_required(login_url=reverse_lazy('account:login'))
def task_new(request, pk):
    action = 'New'
    roadmap = get_object_or_404(Roadmap, pk=pk)
    if request.user == roadmap.user:
        if request.method == 'POST':
            form = TaskForm(request.POST)
            if form.is_valid():
                task = form.save(commit=False)
                task.roadmap = roadmap
                task.save()
                return redirect('roadmap:task', pk=task.pk)
        else:
            form = TaskForm()
        return render(request, 'roadmap/task_edit.html', {'form': form, 'action': action})
    raise PermissionDenied


@login_required(login_url=reverse_lazy('account:login'))
def task_update(request, pk):
    import ipdb; ipdb.set_trace()
    task = get_object_or_404(Task, pk=pk)
    action = 'Update'
    if request.user == task.roadmap.user:
        if request.method == 'POST':
            form = TaskEditForm(request.POST, instance=task)
            if form.is_valid():
                task = form.save(commit=False)
                if task.state == 'ready':
                    task.set_score()
                else:
                    task.unset_score()
                task.save()
                return redirect('roadmap:task', pk=task.pk)
        else:
            form = TaskEditForm(instance=task)
        return render(request, 'roadmap/task_edit.html', {'form': form, 'action': action})
    raise PermissionDenied


@login_required(login_url=reverse_lazy('account:login'))
def task_delete(request, pk):
    task = get_object_or_404(Task, pk=pk)
    roadmap_pk = task.roadmap.pk
    if request.user == task.roadmap.user:
        task.delete()
        return redirect('roadmap:roadmap', pk=roadmap_pk)
    raise PermissionDenied


@login_required(login_url=reverse_lazy('account:login'))
def roadmaps_show(request):
    user = request.user
    roadmaps = user.roadmap_set.all()
    return render(request, 'roadmap/roadmaps.html', {'roadmaps': roadmaps})


@login_required(login_url=reverse_lazy('account:login'))
def roadmap_detail(request, pk):
    roadmap = get_object_or_404(Roadmap, pk=pk)
    if roadmap.user == request.user:
        tasks = Task.objects.filter(roadmap=roadmap).order_by('state', 'estimate')
        return render(request, 'roadmap/roadmap_detail.html', {'roadmap': roadmap, 'tasks': tasks})
    raise PermissionDenied


@login_required(login_url=reverse_lazy('account:login'))
def roadmap_stats(request):
    user = request.user
    roadmaps = user.roadmap_set.all()
    stat_dict = stats(roadmaps)

    sum_score = 0
    for roadmap in roadmaps:
        scores = Score.objects.filter(task__roadmap=roadmap)
        points_earned = scores.aggregate(models.Sum('points'))['points__sum']
        if points_earned is None:
            points_earned = 0
        sum_score += points_earned

    sum_tasks = 0
    for roadmap in roadmaps:
        tasks = Task.objects.filter(roadmap=roadmap).count()
        sum_tasks += tasks
    return render(request, 'roadmap/stat.html', {'weeks': stat_dict['weeks'], 'months': stat_dict['months'],
                                                 'sum_score': sum_score, 'sum_tasks': sum_tasks})


@login_required(login_url=reverse_lazy('account:login'))
def roadmap_new(request):
    if request.method == 'POST':
        form = RoadmapForm(request.POST)
        if form.is_valid():
            roadmap = form.save(commit=False)
            roadmap.user = request.user
            roadmap.save()
            return redirect('roadmap:roadmaps')
    else:
        form = RoadmapForm()
    return render(request, 'roadmap/roadmap_new.html', {'form': form})


@login_required(login_url=reverse_lazy('account:login'))
def roadmap_delete(request, pk):
    roadmap = get_object_or_404(Roadmap, pk=pk)
    if roadmap.user == request.user:
        roadmap.delete()
    else:
        raise PermissionDenied
    return redirect('roadmap:roadmaps')

hw34/templates/roadmap/roadmap_detail.html
{% extends "account/base.html" %} {%block title%}Roadmap`s tasks{% endblock %}
{%block content%}
<div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            
            <div class="modal-body">
                <h3>Вы действительно хотите удалить этот task?</h3>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Нет</button>
                <a class="btn btn-danger btn-ok">Да</a>
            </div>
        </div>
    </div>
</div><div class="wrapper">
    <div class="row col-md-offset-2 col-md-8">
        <h1>Task list for {{ roadmap.name }}</h1>
        <p><a class='btn btn-default' href="{%  url 'roadmap:roadmaps' %}">Back to Roadmaps</a></p>
        <p><a class='btn btn-primary' href="{% url 'roadmap:task_new' pk=roadmap.pk %}">Create new task</a></p>
        <div class="table-responsive ">
        	<table class="table table-hover">
        		{% for task in tasks %}
	            <tr class='row {%if task.is_crit %}danger{% endif %}{% if task.state == "ready" %}success{% endif %}'>
	                <td class='col-md-4'>
	                    <a href="{% url 'roadmap:task' pk=task.pk %}">{{ task.title }}</a></td>
	                <td class='col-md-2'>{{ task.get_state_display }}</td>
	                <td class='col-md-2'>{{ task.estimate }}</td>
	                <td class='col-md-2'><a  data-href="{% url 'roadmap:task_delete' pk=task.pk %}" data-toggle="modal" data-target="#confirm-delete" href="#">Delete task</a></td>
	                <td class='col-md-2'>
	                <a href="{% url 'roadmap:task_edit' pk=task.pk %}">Edit task</a></td>
	            </tr>
         		{% endfor %}
        	</table>
		</div>
    </div>
</div>
<script>$('#confirm-delete').on('show.bs.modal', function(e) {
    $(this).find('.btn-ok').attr('href', $(e.relatedTarget).data('href'));
});</script>
{% endblock %}

hw34/templates/roadmap/roadmap_new.html
{% extends "account/base.html" %} {%block title%}New roadmap{% endblock %} {%block content%}
<div class="wrapper">
    <div class="row col-md-offset-2 col-md-8">
        <h1>New Roadmap</h1>
        <form action="" method="POST">
            <div class="form-group">
                {{ form.name.errors }}
                <label for="id_name">Name:</label>
                {{ form.name }}
            </div>
            {% csrf_token %}
  			<button type="submit" class="btn btn-default">Submit</button>
        </form>
    </div>
</div>
</body>

</html>
{% endblock %}

hw34/templates/roadmap/roadmap_stat.html
{% extends "account/base.html" %} {%block title%}Roadmaps stats{% endblock %}
{%block content%}

<div class="wrapper">
    <div class="row col-md-offset-2 col-md-8">
    <div class="row">
        <h1>Roadmaps Stats</h1>
        <a class='btn btn-default' href="{%  url 'roadmap:roadmaps' %}">Back to Roadmaps</a>
    </div>
    	<h3>Weekly stats</h3>
        <div class="table-responsive ">
        	<table class="table table-hover">
        		<tr class='row'>
	                <th class='col-md-2'>Week number</a></td>
	                <th class='col-md-4'>Interval</td>
	                <th class='col-md-3'>Tasks created</td>
	                <th class='col-md-3'>Tasks completed</td>
	            </tr>
        		{% for week in weeks %}
	            <tr class='row'>
	                <td class='col-md-2'>{{ week.number }}</a></td>
	                <td class='col-md-4'>{{ week.title }}</td>
	                <td class='col-md-3'>{{ week.tasks_created }}</td>
	                <td class='col-md-3'>{{ week.tasks_completed }}</td>
	            </tr>
         		{% endfor %}
        	</table>
		</div>
		<h3>Monthly stats</h3>
	    <div class="table-responsive ">
        	<table class="table table-hover">
        		<tr class='row'>
	                <th class='col-md-2'>Month</a></td>
	                <th class='col-md-4'>Points earned</td>
	            </tr>
        		{% for month in months %}
	            <tr class='row'>
	                <td class='col-md-2'>{{ month.title }}</a></td>
	                <td class='col-md-4'>{{ month.points_earned }}</td>
	            </tr>
         		{% endfor %}
        	</table>
		</div>
    </div>
</div>
{% endblock %}

hw34/templates/roadmap/roadmaps.html
{% extends "account/base.html" %} {% block title %}Roadmap list{% endblock %}
{% block page-title %}
    Список дорожных карт
{% endblock %}
{% block path %}
    <li class="active">Roadmaps</li>
{% endblock %}
{% block content %}
    <div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
         aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">

                <div class="modal-body">
                    <h3>Вы действительно хотите удалить этот roadmap?</h3>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Нет</button>
                    <a class="btn btn-danger btn-ok">Да</a>
                </div>
            </div>
        </div>
    </div>
    <div class="main-wrapper" style="margin-top:20px ;">
        <div class="row col-md-offset-2 col-md-8">
            <div class="panel info-box panel-white">
                <div class="panel-body">


                    <p><a class='btn btn-primary' href="{% url 'roadmap:roadmap_new' %}">Create new Roadmap</a></p>
                    <div class="table-responsive ">
                        <table class="table table-bordered">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Дорожная карта</th>
                                <th>Количество заданий</th>
                                <th>Действие</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for roadmap in roadmaps %}
                                <tr>
                                    <td class='col-md-1' scope="row"> {{ forloop.counter }}</td>
                                    <td class='col-md-7'><a
                                            href="{% url 'roadmap:roadmap' pk=roadmap.pk %}">{{ roadmap.name }}</a></td>
                                    <td class='col-md-2'>{{ roadmap.task_set.all.count }}</td>
                                    <td class='col-md-2'><a data-href="{% url 'roadmap:roadmap_delete' pk=roadmap.pk %}"
                                                            data-toggle="modal" data-target="#confirm-delete" href="#">Delete
                                        Roadmap</a></td>
                                </tr>
                            {% endfor %}</tbody>
                        </table>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <script>$('#confirm-delete').on('show.bs.modal', function (e) {
        $(this).find('.btn-ok').attr('href', $(e.relatedTarget).data('href'));
    });</script>
{% endblock %}

hw34/templates/roadmap/stat.html
{% extends "account/base.html" %} {% block title %}Статистика по заданиям{% endblock %}
{% block page-title %}
    Статистическая информация
{% endblock %}
{% block path %}
    <li class="active">Статистика</li>
{% endblock %}
{% block content %}

    <div id="main-wrapper">
        <div class="row">

            <div class="col-md-offset-2 col-lg-3 col-md-6">
                <div class="panel info-box panel-white">
                    <div class="panel-body">
                        <div class="info-box-stats">
                            <p class="counter">{{ sum_tasks }}</p>
                            <span class="info-box-title">Общее кол-во задач</span>
                        </div>
                        <div class="info-box-icon">
                            <i class="fa fa-users" aria-hidden="true"></i>
                        </div>
                        <div class="info-box-progress">
                            <div class="progress progress-xs progress-squared bs-n">
                                <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="80"
                                     aria-valuemin="0" aria-valuemax="100" style="width: 80%">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="panel info-box panel-white">
                    <div class="panel-body">
                        <div class="info-box-stats">
                            <p><span class="counter">{{ sum_score }}</span></p>
                            <span class="info-box-title">Сумарное кол-во очков</span>
                        </div>
                        <div class="info-box-icon">
                            <i class="fa fa-eye" aria-hidden="true"></i>
                        </div>
                        <div class="info-box-progress">
                            <div class="progress progress-xs progress-squared bs-n">
                                <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="60"
                                     aria-valuemin="0" aria-valuemax="100" style="width: 60%">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="panel info-box panel-white">
                    <div class="panel-body">
                        <div class="info-box-stats">
                            <p class="counter">{{ user.roadmap_set.all.count }}</p>
                            <span class="info-box-title">Кол-во дорожных карт</span>
                        </div>
                        <div class="info-box-icon">
                            <i class="fa fa-usd" aria-hidden="true"></i>
                        </div>
                        <div class="info-box-progress">
                            <div class="progress progress-xs progress-squared bs-n">
                                <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="50"
                                     aria-valuemin="0" aria-valuemax="100" style="width: 50%">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Row -->

        <div class="row">
            <div class="col-sm-offset-2 col-sm-8">
                <div class="panel info-box panel-white">
                    <h3>Weekly stats</h3>
                    <div class="table-responsive ">
                        <table class="table table-hover">
                            <tr class='row'>
                                <th class='col-md-2'>Week number
                                </td>
                                <th class='col-md-4'>Interval
                                </td>
                                <th class='col-md-3'>Tasks created
                                </td>
                                <th class='col-md-3'>Tasks completed
                                </td>
                            </tr>
                            {% for week in weeks %}
                                <tr class='row'>
                                    <td class='col-md-2'>{{ week.number }}</td>
                                    <td class='col-md-4'>{{ week.title }}</td>
                                    <td class='col-md-3'>{{ week.tasks_created }}</td>
                                    <td class='col-md-3'>{{ week.tasks_completed }}</td>
                                </tr>
                            {% endfor %}
                        </table>
                    </div>
                    <h3>Monthly stats</h3>
                    <div class="table-responsive ">
                        <table class="table table-hover">
                            <tr class='row'>
                                <th class='col-md-2'>Month</a>
                                </td>
                                <th class='col-md-4'>Points earned
                                </td>
                            </tr>
                            {% for month in months %}
                                <tr class='row'>
                                    <td class='col-md-2'>{{ month.title }}</a></td>
                                    <td class='col-md-4'>{{ month.points_earned }}</td>
                                </tr>
                            {% endfor %}
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

hw34/templates/roadmap/task.html
{% extends "account/base.html" %} {%block title%}task {{task.pk}}{% endblock %}
{%block content%}
<div class="wrapper">
    <div class="row col-md-offset-2 col-md-8">
		<h1{%if task.is_crit %} style="color:red;"{%endif%}>{{ task.title }}</h1>
	    <p>Task estimate: {{ task.estimate }} </p>
	    <p>Task state: {{ task.get_state_display }} </p>
	    {% if task.score %}<p>Task points: {{ task.score.points }} </p>{% endif %}

	    <a href="{% url 'roadmap:task_edit' pk=task.pk %}">Edit task</a>
	    <p><a class='btn btn-default' href="{%  url 'roadmap:roadmap' pk=task.roadmap.pk %}">Back to Roadmap</a></p>
	</div>
</div>	
</div>
{% endblock %}

hw34/templates/roadmap/task_edit.html
{% extends "account/base.html" %} {%block title%}task update{% endblock %}
{%block content%}
<div class="wrapper">
    <div class="row col-md-offset-2 col-md-8">
	<h1>{{ action }} task</h1>
    {% if msg %}
        {{ msg }}
    {% endif %}
	<form action="" method="POST">
		<div class="field">
            {{ form.title.errors }}
            <label for="id_title">Title:</label>
            {{ form.title }}
        </div>
        {% if action == "Update" %} 
            <div class="field">
                {{ form.state.errors }}
                <label for="id_state">State:</label>
                {{ form.state }}
            </div>
        {% endif %} 
        <div class="field">
            {{ form.estimate.errors }}
            <label for="id_estimate">Estimate:</label>
            {{ form.estimate }}
        </div>

		{% csrf_token %}
		<input type="submit" value="Submit">
	</form>
    </div>  
</div>
{% endblock %}