hw34/account/urls.py
from django.conf.urls import url
from .views import LoginFormView, RegisterFormView, LogoutView, UserChangeFormView
from .views import change_password, profile_view
app_name = 'account'

urlpatterns = [
    url(r'^login/$', LoginFormView.as_view(), name='login'),
    url(r'^signup/$', RegisterFormView.as_view(), name='reg'),
    url(r'^password/$', change_password, name='change_pass'),
    url(r'^settings/$', UserChangeFormView.as_view(), name='settings'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^$', profile_view, name='profile'),

]

hw34/hw3/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views
urlpatterns = [
    url(r'^admin/',include(admin.site.urls)),
    url(r'^$', views.index, name='index'),
    url(r'^account/', include('account.urls')),
    url(r'^', include('roadmap.urls')),
]

hw34/hw3/views.py
from django.shortcuts import render, get_object_or_404, redirect

def index(request):
	return render(request, 'hw3/index.html')

hw34/templates/hw3/index.html
<!doctype html>
<html lang="ru">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>TASK TRACKER - ПРОЕКТ ТЕХНОАТОМА</title>
    <link rel="shortcut icon" href="https://cdn.auth0.com/styleguide/components/1.0.8/media/logos/img/favicon.png">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Roboto&amp;subset=cyrillic" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'land.css' %}">
</head>
<body>
<div id="banner">
    <div class="header-wrapper">
        <div class="header-inner">
            <div class="row">
                <div id="logo" class="col-md-3">
                    <a href="http://demos.shapingrain.com/inbound/" rel="home">
                        <img src="http://demos.shapingrain.com/inbound/wp-content/uploads/sites/18/inbound_exports/inbound-software-925/inbound-logo.png"
                             alt="Inbound" title="Inbound" class="logo-primary">
                    </a>
                </div>
                <div class="nav-wrapper clearfix col-md-offset-4 col-md-5">
                    <ul class="nav navbar-nav pull-right">
                        <li><a href="#adv">Возможности</a></li>
                        <li><a href="#contact">Контакты</a></li>
                        <li><a href="{% url 'account:login' %}">Вход</a></li>
                        <li><a href="{% url 'account:reg' %}">Регистрация</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="banner-content container">
        <div class="row">
            <div class="top text-center">
                <h1>Менеджер задач</h1>
                <hr class="devide">
                <h3>Лучший способ управлениями процессами и задачами</h3>
                <a href="{% url 'account:reg' %}" class="btn btn-success btn-lg">
                    <div>Регистрация</div>
                </a>
            </div>
        </div>
        <div class="row">
            <div class="note-wrapper">
                <div class="note">
                    <img class="img-responsive"
                         src="http://demos.shapingrain.com/inbound/wp-content/uploads/sites/18/inbound_exports/inbound-software-925/software-laptop.png"
                         alt="software-laptop">
                </div>
            </div>
        </div>
    </div>
</div>
<div class="main">
    <div class="container how" id="adv">
        <div class="row">
            <hr class="devide" style="border-color: darkorange;">
            <div class="col-md-12 text-center">
                <h2 class="title">Возможности</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4 text-center">
                <div  class="icon"><img
                        src="http://demos.shapingrain.com/inbound/wp-content/uploads/sites/18/inbound_exports/inbound-software-925/software-icon-1-1.png"
                        alt="Connect with your customers"></div>
                <h4>Облачная платформа</h4>
                <p>Сохраняй свои задачи на одном устройстве, смотри с любого, с технологией облачного хранения
                    данных</p>
            </div>
            <div class="col-md-4 text-center">
                <div class="icon"><img
                        src="http://demos.shapingrain.com/inbound/wp-content/uploads/sites/18/inbound_exports/inbound-software-925/software-icon-2-1.png"
                        alt="Connect with your customers"></div>
                <h4>Детальная статистика</h4>
                <p>Статистика и Графики выполнения всех задач и карт. Интуитивная возможность управления данными</p>
            </div>
            <div class="col-md-4 text-center">
                <div class="icon"><img
                        src="http://demos.shapingrain.com/inbound/wp-content/uploads/sites/18/inbound_exports/inbound-software-925/software-icon-3-1.png"
                        alt="Connect with your customers"></div>
                <h4>Удобный интерфейс</h4>
                <p>Приятный способ управления задачами на любом устройсте</p>
            </div>

        </div>
        <div class="row">
            <div class="col-md-offset-5 col-md-2">
                <a href="{% url 'account:reg' %}" class="btn btn-warning" style="padding:20px;margin-top:40px;">Начать
                    пользоваться</a>
            </div>
        </div>
    </div>
</div>
<footer class="clearfix">
    <div class="container">
        <div class="row">
            <ul class="list-unstyled">
                <li class="list-item"><a href="">Правила</a></li>
            </ul>
        </div>
    </div>
</footer>
</body>
</html>